"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class Event(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    JSON_FIELD_NUMBER: _builtins.int
    json: _builtins.str
    def __init__(
        self,
        *,
        json: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["json", b"json"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class CommandRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMAND_FIELD_NUMBER: _builtins.int
    JSON_ARGS_FIELD_NUMBER: _builtins.int
    JSON_KWARGS_FIELD_NUMBER: _builtins.int
    command: _builtins.str
    json_args: _builtins.str
    json_kwargs: _builtins.str
    def __init__(
        self,
        *,
        command: _builtins.str = ...,
        json_args: _builtins.str = ...,
        json_kwargs: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command", b"command", "json_args", b"json_args", "json_kwargs", b"json_kwargs"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommandRequest: _TypeAlias = CommandRequest  # noqa: Y015

@_typing.final
class CommandReply(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EVENT_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def event(self) -> Global___Event: ...
    def __init__(
        self,
        *,
        event: Global___Event | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["event", b"event"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CommandReply: _TypeAlias = CommandReply  # noqa: Y015

@_typing.final
class SubscribeRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

Global___SubscribeRequest: _TypeAlias = SubscribeRequest  # noqa: Y015
