# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from mcutils import meshcore_pb2 as mcutils_dot_meshcore__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mcutils/meshcore_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MeshCoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.subscribe = channel.unary_stream(
                '/mcutils.MeshCore/subscribe',
                request_serializer=mcutils_dot_meshcore__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=mcutils_dot_meshcore__pb2.Event.FromString,
                _registered_method=True)
        self.command = channel.unary_unary(
                '/mcutils.MeshCore/command',
                request_serializer=mcutils_dot_meshcore__pb2.CommandRequest.SerializeToString,
                response_deserializer=mcutils_dot_meshcore__pb2.CommandReply.FromString,
                _registered_method=True)


class MeshCoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def command(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MeshCoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.subscribe,
                    request_deserializer=mcutils_dot_meshcore__pb2.SubscribeRequest.FromString,
                    response_serializer=mcutils_dot_meshcore__pb2.Event.SerializeToString,
            ),
            'command': grpc.unary_unary_rpc_method_handler(
                    servicer.command,
                    request_deserializer=mcutils_dot_meshcore__pb2.CommandRequest.FromString,
                    response_serializer=mcutils_dot_meshcore__pb2.CommandReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mcutils.MeshCore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('mcutils.MeshCore', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MeshCore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/mcutils.MeshCore/subscribe',
            mcutils_dot_meshcore__pb2.SubscribeRequest.SerializeToString,
            mcutils_dot_meshcore__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def command(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/mcutils.MeshCore/command',
            mcutils_dot_meshcore__pb2.CommandRequest.SerializeToString,
            mcutils_dot_meshcore__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
